routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/

Route::get('/', ['as'=>"home.index", "uses"=>"HomeController@index"]);
Route::group(['middleware'=>["auth"], 'namespace'=>"Web"], function()
{
    Route::resource('teams', 'TeamsController');
    Route::resource('flights', 'FlightsController');
    Route::resource('routes', 'RoutesController');
    Route::resource('units', 'UnitsController');
    Route::resource('storage', 'StorageController');

    Route::group(["prefix"=>"settings", 'namespace'=>"settings"], function ()
    {
        Route::resource('teams', 'TeamsController');
        Route::resource('teams.invitation', 'TeamInvitationController');
        Route::resource('teams.subscription','TeamSubscriptionController');
        Route::resource('payments_methods', 'PaymentMethodsController');
        Route::resource('users', 'UsersController');
    });

});




Auth::routes();

Route::get('/home', 'HomeController@index');

app/Http/Controllers/Web/RoutesController.php
<?php

namespace App\Http\Controllers\Web;

use App\FlightRoute;
use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;

class RoutesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $flightRoutes = FlightRoute::paginate(10);
        return view('routes.index', compact('flightRoutes'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('routes.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, ['destination'=>"required", 'origin'=>"required", "flight_number"=>"required|integer"]);
        $airlineId = $request->get('airline_id');

        $route = new FlightRoute($request->all());
        $route->airline()->associate($airlineId);
        $route->save();

        return redirect()->route('routes.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/routes/create.blade.php
@extends('layouts.app')
@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="page-header">
                    <h1>Route create</h1>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <form action="{{ route('routes.store') }}" method="post">
                    {{ csrf_field() }}
                    <div class="panel panel-default">
                        <div class="panel-body">
                            @include('routes.partials._form')
                        </div>
                        <div class="panel-footer">
                            <button type="submit" class="btn btn-primary">Save</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
@stop

resources/views/routes/index.blade.php
@extends('layouts.app')
@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="page-header">
                    <h1>Flight Routes</h1>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <div class="table-responsive">
                            <table class="table table-striped">
                                <thead>
                                <tr>
                                    <th>Flight number</th>
                                    <th>Origin</th>
                                    <th>Destination</th>
                                    <th>Action</th>
                                </tr>
                                </thead>
                                <tbody>
                                @foreach($flightRoutes as $flightRoute)
                                    <tr>
                                        <td>
                                            {{ $flightRoute->flightNumber() }}
                                        </td>
                                        <td>
                                            {{ $flightRoute->origin }}
                                        </td>
                                        <td>
                                            {{ $flightRoute->destination }}
                                        </td>
                                        <td></td>
                                    </tr>
                                @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                    <div class="panel-footer">
                        <a href="{{ route('routes.create') }}" class="btn btn-default">Create</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
@stop